services:
  mailbox-mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mailbox-mosquitto
    ports:
      - "8883:8883"
    restart: on-failure
    volumes:
      - ./certs/ca.crt:/mosquitto/ca.crt:rw
      - ./certs/server.key:/mosquitto/server.key:rw
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:rw

  mqtt_consumer:
    container_name: mqtt_consumer
    build:
      context: ./mqtt_consumer/
      dockerfile: Dockerfile
    depends_on:
      - mailbox-mosquitto
    environment:
      MQTT_BROKER: mailbox-mosquitto 
      MQTT_PORT: 8883
      MQTT_TOPIC: home/mailbox
      DISCORD_URL: ${DISCORD_URL}
      ESP_CHECKIN_TIME_IN_HOURS: 2
      ESP_STANDARD_DISTANCE_IN_MM: 110
    restart: on-failure
    volumes:
      - ./certs/ca.crt:/certs/ca.crt:ro
      - ./certs/mqttConsumer.crt:/certs/mqttConsumer.crt:ro
      - ./certs/mqttConsumer.key:/certs/mqttConsumer.key:ro
      - ./mqtt_consumer/mqtt_consumer.py:/app/mqtt_consumer.py:ro
