services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "8883:8883"
    restart: always
    volumes:
      - ./certs/ca.crt:/mosquitto/ca.crt:ro
      - ./certs/server.key:/mosquitto/server.key:ro
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  mqtt_consumer:
    container_name: mqtt_consumer
    build:
      context: ./mqtt_consumer/
      dockerfile: Dockerfile
    depends_on:
      - mosquitto
    environment:
      MQTT_BROKER: mosquitto
      MQTT_PORT: 8883
      MQTT_TOPIC: temp
    restart: always
    volumes:
      - ./certs/ca.crt:/certs/ca.crt:ro
      - ./certs/mqttConsumer.crt:/certs/mqttConsumer.crt:ro
      - ./certs/mqttConsumer.key:/certs/mqttConsumer.key:ro
      - ./mqtt_consumer/mqtt_consumer.py:/app/mqtt_consumerpy:ro
      - ./mqtt_consumer/requirements.txt:/app/requirements.txt:ro
